name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build the Docker image
        run: docker build -t cygnetops/react-test -f Dockerfile.dev .
      - name: Run the Docker image
        run: docker run -e CI=true cygnetops/react-test npm test